source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.3'
inhibit_all_warnings!
use_frameworks!

workspace 'PodTest'

target 'PodTest' do
    pod 'ROGoogleTranslate'
    pod 'Parse/Core', '1.17.1'
    pod 'Parse/FacebookUtils', '1.17.1'
    pod 'Bolts', '1.9.0'
    pod 'Bolts-Swift', '1.4.0'
    pod 'JSQMessagesViewController', '7.3.3'
    pod 'FBSDKCoreKit', '~> 4.28.0'
    pod 'FBSDKShareKit', '~> 4.28.0'
    pod 'FBSDKLoginKit', '~> 4.28.0'
    pod 'ParseUI', '1.2.0'
    pod 'ParseLiveQuery', git: 'https://github.com/zackshapiro/ParseLiveQuery-iOS-OSX'
    pod 'FastttCamera', '0.3.4'
    pod 'SpinKit', '~> 1.1'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'Fabric', '~> 1.6'
    pod 'Crashlytics', '~>  3.8'
    pod 'BASSquareCropper', '~> 0.0'
    pod 'TOWebViewController', '~> 2.2.6'
    pod 'DGActivityIndicatorView', '2.1.1'
    pod 'HNKGooglePlacesAutocomplete', '~> 1.1'
    pod 'QBImagePickerController', '3.4.0'
    pod 'iCarousel', '~> 1.8'
    pod 'BLKFlexibleHeightBar', '1.0.2'
    pod 'HMSegmentedControl'
    pod 'SDWebImage', '~>3.8'
    pod 'SwipeView', '~> 1.3'
    pod 'FXBlurView', '~> 1.6'
    pod 'LXReorderableCollectionViewFlowLayout', '0.2.1'
    pod 'UIImageView-Letters', '1.1.4'
    pod 'NMRangeSlider', '~> 1.2'
    pod 'Transcontinental', '~> 1.0'
    pod 'CountryPicker', '~> 1.3'
    pod 'YLProgressBar', '~> 3.10.1'
    pod 'Mixpanel', '~> 3.3.0'
    pod 'Intercom', '5.0.0'
    pod 'MZTimerLabel', '0.5.4'
    pod 'Branch', '~> 0.24.2'
    pod 'libPhoneNumber-iOS', '~> 0.8'
    pod 'SlackTextViewController', '~> 1.9.6'
    pod 'Cartography', '~> 3.0.2'
    pod 'ReactiveSwift'
end

